docs: migrate URLs from `docker.pkg.github.com` to `ghcr.io`
- Per https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-docker-registry and https://docs.github.com/en/packages/working-with-a-github-packages-registry/migrating-to-the-container-registry-from-the-docker-registry, GitHub's Docker Registry under `docker.pkg.github.com` was replaced by its Container Registry at `ghcr.io`
  - all the GitHub Packages all say to use `ghcr.io` as well; for instance https://github.com/knonomura/griddb-docker/pkgs/container/griddb-docker%2Fpython-client shows `docker pull ghcr.io/knonomura/griddb-docker/python-client:0.1`
  - so update all URLs to use `ghcr.io` now

- without this change, I was getting 403 errors trying to pull any of the images:
```sh
❯ podman pull docker.pkg.github.com/knonomura/griddb-docker/python-client:0.1
Trying to pull docker.pkg.github.com/knonomura/griddb-docker/python-client:0.1...
Error: initializing source docker://docker.pkg.github.com/knonomura/griddb-docker/python-client:0.1: reading manifest 0.1 in docker.pkg.github.com/knonomura/griddb-docker/python-client: denied
```